# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be2a68530b30c8c08ea535628039a9a2ccfa5e75746974129bc09aeec06a1736bb5b4eb6a2413b684b6b58a08a0e12c833051c84535093a9608698a241d4618f

test:
  secret_key_base: a10c57f5e0916a40f3400bfbed0d35ab0b6e6f04d85d185e27c9fed5b68eb9bd6c4193ff5063a92bf18eb343323c1ce15e9bbce280589bc080229d9681318f53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
